providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1727136237'

[variables]
CI = "true"
NIXPACKS_METADATA = "node"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.build]
dependsOn = ['install']
cmds = ['pnpm run build --filter=initial-upload...']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = [
    'npm install -g corepack@0.24.1 && corepack enable',
    'pnpm install --filter=initial-upload...',
]
cacheDirectories = ['/root/.local/share/pnpm/store/v3']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = ['bun', 'ffmpeg_6', 'nodejs_22', 'pnpm', 'openssl']
nixLibs = ['gcc-unwrapped']
nixOverlays = []
aptPkgs = []

[start]
cmd = 'bun run workers/initial-upload/build/index.js'
