providers = ['turborepo']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1727136237'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['install']
cmds = ['pnpm run build']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = [
    'npm install -g corepack@0.24.1 && corepack enable',
    'pnpm i --frozen-lockfile',
]
cacheDirectories = ['/root/.local/share/pnpm/store/v3']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = ['bun', 'ffmpeg_6', 'nodejs_22', 'pnpm-9_x', 'openssl']
nixLibs = ['gcc-unwrapped']
nixOverlays = []
nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'
aptPkgs = []

[start]
cmd = 'pnpm start --filter=thumbnail'
